db = db.getSiblingDB('poe_pet');

db.shop_items.deleteMany({});
db.shop_items.insertMany([
  { code: "food_small_50", type: "CONSUMABLE", shopSection: "CONSUMABLES", name: "Meal Pack +50", description: "Feeds pet for 50 hunger points.", priceCoins: 10, effects: [{ kind: "HUNGER_ADD", value: 50 }], stackable: true, oneTimePurchase: false, active: true, playerVisible: true, effectKey: null },
  { code: "food_boost_20_regen_10pct_10h", type: "CONSUMABLE", shopSection: "CONSUMABLES", name: "Boost Snack +20", description: "Feeds +20 hunger and boosts energy regeneration by 10% for 10 hours.", priceCoins: 10, effects: [{ kind: "HUNGER_ADD", value: 20 }, { kind: "ENERGY_REGEN_MULTIPLIER", value: 0.1, durationHours: 10, effectName: "fast_regen" }], stackable: true, oneTimePurchase: false, active: true, playerVisible: true, effectKey: "fast_regen" },
  { code: "food_combo_10_energy_25pct", type: "CONSUMABLE", shopSection: "CONSUMABLES", name: "Quick Bite +10", description: "Feeds +10 hunger and restores 25% energy instantly.", priceCoins: 10, effects: [{ kind: "HUNGER_ADD", value: 10 }, { kind: "ENERGY_PERCENT_ADD", value: 0.25 }], stackable: true, oneTimePurchase: false, active: true, playerVisible: true, effectKey: null },
  { code: "food_cozy_bites", type: "CONSUMABLE", shopSection: "CONSUMABLES", name: "Cozy Bites", description: "Small treat: +12 hunger and +15 happiness.", priceCoins: 12, effects: [{ kind: "HUNGER_ADD", value: 12 }, { kind: "HAPPINESS_ADD", value: 15 }], stackable: true, oneTimePurchase: false, active: true, playerVisible: true, effectKey: null },
  { code: "snack_coin_boost", type: "CONSUMABLE", shopSection: "CONSUMABLES", name: "Lucky Syrup (+20% coins)", description: "Feeds +5 hunger and multiplies coin rewards from minigames by 1.2 for 4 hours.", priceCoins: 15, effects: [{ kind: "HUNGER_ADD", value: 5 }, { kind: "COIN_MULTIPLIER", value: 1.2, durationHours: 4 }], stackable: true, oneTimePurchase: false, active: true, playerVisible: true, effectKey: "gold_rush" },
  { code: "resurrection_basic", type: "CONSUMABLE", shopSection: "CONSUMABLES", name: "Revive Snack", description: "Sets hunger, happiness and energy to 10%.", priceCoins: 200, effects: [{ kind: "SET_HUNGER_PERCENT", value: 0.1 }, { kind: "SET_HAPPINESS_PERCENT", value: 0.1 }, { kind: "SET_ENERGY_PERCENT", value: 0.1 }], stackable: true, oneTimePurchase: false, active: true, playerVisible: true, effectKey: null },
  { code: "cosmetic_bg_aurora", type: "COSMETIC", shopSection: "COSMETICS", name: "Scene: Aurora Hills", description: "Unlocks this background for your pet stage (equip in Customize).", priceCoins: 40, effects: [{ kind: "GRANT_VISUAL", visualAssetCode: "bg_aurora_default" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "cosmetic_bg_candy", type: "COSMETIC", shopSection: "COSMETICS", name: "Scene: Candy Dream", description: "Unlocks this background for your pet stage.", priceCoins: 40, effects: [{ kind: "GRANT_VISUAL", visualAssetCode: "bg_candy_default" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "cosmetic_bg_dusk", type: "COSMETIC", shopSection: "COSMETICS", name: "Scene: Dusk Glow", description: "Unlocks this background for your pet stage.", priceCoins: 45, effects: [{ kind: "GRANT_VISUAL", visualAssetCode: "bg_dusk_default" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "cosmetic_bg_underwater", type: "COSMETIC", shopSection: "COSMETICS", name: "Scene: Underwater", description: "Unlocks this background for your pet stage.", priceCoins: 45, effects: [{ kind: "GRANT_VISUAL", visualAssetCode: "bg_underwater_default" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "cosmetic_fg_sparkle", type: "COSMETIC", shopSection: "COSMETICS", name: "Overlay: Sparkle Frame", description: "Unlocks a soft sparkle foreground overlay.", priceCoins: 35, effects: [{ kind: "GRANT_VISUAL", visualAssetCode: "fg_sparkle_default" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "species_penguin", type: "SPECIES", shopSection: "SPECIES", name: "Pet: Chubby Penguin", description: "Unlocks Penguin as a selectable pet.", priceCoins: 1000, effects: [{ kind: "GRANT_SPECIES", speciesCode: "penguin" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "species_fox", type: "SPECIES", shopSection: "SPECIES", name: "Pet: Little Cheeky Fox", description: "Unlocks Fox as a selectable pet.", priceCoins: 1000, effects: [{ kind: "GRANT_SPECIES", speciesCode: "fox" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "species_hamster", type: "SPECIES", shopSection: "SPECIES", name: "Pet: Stuffed-Cheek Hamster", description: "Unlocks Hamster as a selectable pet.", priceCoins: 1000, effects: [{ kind: "GRANT_SPECIES", speciesCode: "hamster" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "species_tiger", type: "SPECIES", shopSection: "SPECIES", name: "Pet: Little Tiger Cub", description: "Unlocks Tiger as a selectable pet.", priceCoins: 1000, effects: [{ kind: "GRANT_SPECIES", speciesCode: "tiger" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "species_lion", type: "SPECIES", shopSection: "SPECIES", name: "Pet: Lion Cub", description: "Unlocks Lion as a selectable pet.", priceCoins: 1000, effects: [{ kind: "GRANT_SPECIES", speciesCode: "lion" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "species_horse", type: "SPECIES", shopSection: "SPECIES", name: "Pet: Horse", description: "Unlocks Horse as a selectable pet.", priceCoins: 1000, effects: [{ kind: "GRANT_SPECIES", speciesCode: "horse" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "species_parrot", type: "SPECIES", shopSection: "SPECIES", name: "Pet: Parrot", description: "Unlocks Parrot as a selectable pet.", priceCoins: 1000, effects: [{ kind: "GRANT_SPECIES", speciesCode: "parrot" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "species_panda", type: "SPECIES", shopSection: "SPECIES", name: "Pet: Chubby Clueless Panda", description: "Unlocks Panda as a selectable pet.", priceCoins: 1000, effects: [{ kind: "GRANT_SPECIES", speciesCode: "panda" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "species_goldfish", type: "SPECIES", shopSection: "SPECIES", name: "Pet: Goldfish Aquarium", description: "Unlocks Goldfish as a selectable pet.", priceCoins: 1000, effects: [{ kind: "GRANT_SPECIES", speciesCode: "goldfish" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "species_lizard", type: "SPECIES", shopSection: "SPECIES", name: "Pet: Little Lizard", description: "Unlocks Lizard as a selectable pet.", priceCoins: 1000, effects: [{ kind: "GRANT_SPECIES", speciesCode: "lizard" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "species_unicorn", type: "SPECIES", shopSection: "SPECIES", name: "Legendary Pet: Unicorn", description: "Unlocks Unicorn as a selectable legendary pet.", priceCoins: 3000, effects: [{ kind: "GRANT_SPECIES", speciesCode: "unicorn" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null },
  { code: "species_midnight_cat", type: "SPECIES", shopSection: "SPECIES", name: "Legendary Pet: Midnight Cat", description: "Unlocks Midnight Cat as a selectable legendary pet.", priceCoins: 3000, effects: [{ kind: "GRANT_SPECIES", speciesCode: "midnight_cat" }], stackable: false, oneTimePurchase: true, active: true, playerVisible: true, effectKey: null }
]);

db.pet_visual_assets.deleteMany({});
db.pet_visual_assets.insertMany([
  { code: "dog_happy_default", assetType: "PET_MOOD", speciesCode: "dog", moodCode: "happy", label: "Dog Happy (Default)", imagePath: "/pet-assets/dog/happy-default.png", starter: true, active: true },
  { code: "dog_sad_default", assetType: "PET_MOOD", speciesCode: "dog", moodCode: "sad", label: "Dog Sad (Default)", imagePath: "/pet-assets/dog/sad-default.png", starter: true, active: true },
  { code: "dog_hungry_default", assetType: "PET_MOOD", speciesCode: "dog", moodCode: "hungry", label: "Dog Hungry (Default)", imagePath: "/pet-assets/dog/hungry-default.png", starter: true, active: true },
  { code: "dog_tired_default", assetType: "PET_MOOD", speciesCode: "dog", moodCode: "tired", label: "Dog Tired (Default)", imagePath: "/pet-assets/dog/tired-default.png", starter: true, active: true },
  { code: "dog_thinking_default", assetType: "PET_MOOD", speciesCode: "dog", moodCode: "thinking", label: "Dog Thinking (Default)", imagePath: "/pet-assets/dog/thinking-default.png", starter: true, active: true },
  { code: "dog_playing_dead_default", assetType: "PET_MOOD", speciesCode: "dog", moodCode: "playing_dead", label: "Dog Playing Dead (Default)", imagePath: "/pet-assets/dog/playing-dead-default.png", starter: true, active: true },
  { code: "cat_happy_default", assetType: "PET_MOOD", speciesCode: "cat", moodCode: "happy", label: "Cat Happy (Default)", imagePath: "/pet-assets/cat/happy-default.png", starter: true, active: true },
  { code: "cat_sad_default", assetType: "PET_MOOD", speciesCode: "cat", moodCode: "sad", label: "Cat Sad (Default)", imagePath: "/pet-assets/cat/sad-default.png", starter: true, active: true },
  { code: "cat_hungry_default", assetType: "PET_MOOD", speciesCode: "cat", moodCode: "hungry", label: "Cat Hungry (Default)", imagePath: "/pet-assets/cat/hungry-default.png", starter: true, active: true },
  { code: "cat_tired_default", assetType: "PET_MOOD", speciesCode: "cat", moodCode: "tired", label: "Cat Tired (Default)", imagePath: "/pet-assets/cat/tired-default.png", starter: true, active: true },
  { code: "cat_thinking_default", assetType: "PET_MOOD", speciesCode: "cat", moodCode: "thinking", label: "Cat Thinking (Default)", imagePath: "/pet-assets/cat/thinking-default.png", starter: true, active: true },
  { code: "cat_playing_dead_default", assetType: "PET_MOOD", speciesCode: "cat", moodCode: "playing_dead", label: "Cat Playing Dead (Default)", imagePath: "/pet-assets/cat/playing-dead-default.png", starter: true, active: true },
  { code: "penguin_happy_default", assetType: "PET_MOOD", speciesCode: "penguin", moodCode: "happy", label: "Penguin Happy (Default)", imagePath: "/pet-assets/penguin/happy-default.png", starter: true, active: true },
  { code: "penguin_sad_default", assetType: "PET_MOOD", speciesCode: "penguin", moodCode: "sad", label: "Penguin Sad (Default)", imagePath: "/pet-assets/penguin/sad-default.png", starter: true, active: true },
  { code: "penguin_hungry_default", assetType: "PET_MOOD", speciesCode: "penguin", moodCode: "hungry", label: "Penguin Hungry (Default)", imagePath: "/pet-assets/penguin/hungry-default.png", starter: true, active: true },
  { code: "penguin_tired_default", assetType: "PET_MOOD", speciesCode: "penguin", moodCode: "tired", label: "Penguin Tired (Default)", imagePath: "/pet-assets/penguin/tired-default.png", starter: true, active: true },
  { code: "penguin_thinking_default", assetType: "PET_MOOD", speciesCode: "penguin", moodCode: "thinking", label: "Penguin Thinking (Default)", imagePath: "/pet-assets/penguin/thinking-default.png", starter: true, active: true },
  { code: "penguin_playing_dead_default", assetType: "PET_MOOD", speciesCode: "penguin", moodCode: "playing_dead", label: "Penguin Playing Dead (Default)", imagePath: "/pet-assets/penguin/playing-dead-default.png", starter: true, active: true },
  { code: "fox_happy_default", assetType: "PET_MOOD", speciesCode: "fox", moodCode: "happy", label: "Fox Happy (Default)", imagePath: "/pet-assets/fox/happy-default.png", starter: true, active: true },
  { code: "fox_sad_default", assetType: "PET_MOOD", speciesCode: "fox", moodCode: "sad", label: "Fox Sad (Default)", imagePath: "/pet-assets/fox/sad-default.png", starter: true, active: true },
  { code: "fox_hungry_default", assetType: "PET_MOOD", speciesCode: "fox", moodCode: "hungry", label: "Fox Hungry (Default)", imagePath: "/pet-assets/fox/hungry-default.png", starter: true, active: true },
  { code: "fox_tired_default", assetType: "PET_MOOD", speciesCode: "fox", moodCode: "tired", label: "Fox Tired (Default)", imagePath: "/pet-assets/fox/tired-default.png", starter: true, active: true },
  { code: "fox_thinking_default", assetType: "PET_MOOD", speciesCode: "fox", moodCode: "thinking", label: "Fox Thinking (Default)", imagePath: "/pet-assets/fox/thinking-default.png", starter: true, active: true },
  { code: "fox_playing_dead_default", assetType: "PET_MOOD", speciesCode: "fox", moodCode: "playing_dead", label: "Fox Playing Dead (Default)", imagePath: "/pet-assets/fox/playing-dead-default.png", starter: true, active: true },
  { code: "hamster_happy_default", assetType: "PET_MOOD", speciesCode: "hamster", moodCode: "happy", label: "Hamster Happy (Default)", imagePath: "/pet-assets/hamster/happy-default.png", starter: true, active: true },
  { code: "hamster_sad_default", assetType: "PET_MOOD", speciesCode: "hamster", moodCode: "sad", label: "Hamster Sad (Default)", imagePath: "/pet-assets/hamster/sad-default.png", starter: true, active: true },
  { code: "hamster_hungry_default", assetType: "PET_MOOD", speciesCode: "hamster", moodCode: "hungry", label: "Hamster Hungry (Default)", imagePath: "/pet-assets/hamster/hungry-default.png", starter: true, active: true },
  { code: "hamster_tired_default", assetType: "PET_MOOD", speciesCode: "hamster", moodCode: "tired", label: "Hamster Tired (Default)", imagePath: "/pet-assets/hamster/tired-default.png", starter: true, active: true },
  { code: "hamster_thinking_default", assetType: "PET_MOOD", speciesCode: "hamster", moodCode: "thinking", label: "Hamster Thinking (Default)", imagePath: "/pet-assets/hamster/thinking-default.png", starter: true, active: true },
  { code: "hamster_playing_dead_default", assetType: "PET_MOOD", speciesCode: "hamster", moodCode: "playing_dead", label: "Hamster Playing Dead (Default)", imagePath: "/pet-assets/hamster/playing-dead-default.png", starter: true, active: true },
  { code: "tiger_happy_default", assetType: "PET_MOOD", speciesCode: "tiger", moodCode: "happy", label: "Tiger Happy (Default)", imagePath: "/pet-assets/tiger/happy-default.png", starter: true, active: true },
  { code: "tiger_sad_default", assetType: "PET_MOOD", speciesCode: "tiger", moodCode: "sad", label: "Tiger Sad (Default)", imagePath: "/pet-assets/tiger/sad-default.png", starter: true, active: true },
  { code: "tiger_hungry_default", assetType: "PET_MOOD", speciesCode: "tiger", moodCode: "hungry", label: "Tiger Hungry (Default)", imagePath: "/pet-assets/tiger/hungry-default.png", starter: true, active: true },
  { code: "tiger_tired_default", assetType: "PET_MOOD", speciesCode: "tiger", moodCode: "tired", label: "Tiger Tired (Default)", imagePath: "/pet-assets/tiger/tired-default.png", starter: true, active: true },
  { code: "tiger_thinking_default", assetType: "PET_MOOD", speciesCode: "tiger", moodCode: "thinking", label: "Tiger Thinking (Default)", imagePath: "/pet-assets/tiger/thinking-default.png", starter: true, active: true },
  { code: "tiger_playing_dead_default", assetType: "PET_MOOD", speciesCode: "tiger", moodCode: "playing_dead", label: "Tiger Playing Dead (Default)", imagePath: "/pet-assets/tiger/playing-dead-default.png", starter: true, active: true },
  { code: "lion_happy_default", assetType: "PET_MOOD", speciesCode: "lion", moodCode: "happy", label: "Lion Happy (Default)", imagePath: "/pet-assets/lion/happy-default.png", starter: true, active: true },
  { code: "lion_sad_default", assetType: "PET_MOOD", speciesCode: "lion", moodCode: "sad", label: "Lion Sad (Default)", imagePath: "/pet-assets/lion/sad-default.png", starter: true, active: true },
  { code: "lion_hungry_default", assetType: "PET_MOOD", speciesCode: "lion", moodCode: "hungry", label: "Lion Hungry (Default)", imagePath: "/pet-assets/lion/hungry-default.png", starter: true, active: true },
  { code: "lion_tired_default", assetType: "PET_MOOD", speciesCode: "lion", moodCode: "tired", label: "Lion Tired (Default)", imagePath: "/pet-assets/lion/tired-default.png", starter: true, active: true },
  { code: "lion_thinking_default", assetType: "PET_MOOD", speciesCode: "lion", moodCode: "thinking", label: "Lion Thinking (Default)", imagePath: "/pet-assets/lion/thinking-default.png", starter: true, active: true },
  { code: "lion_playing_dead_default", assetType: "PET_MOOD", speciesCode: "lion", moodCode: "playing_dead", label: "Lion Playing Dead (Default)", imagePath: "/pet-assets/lion/playing-dead-default.png", starter: true, active: true },
  { code: "horse_happy_default", assetType: "PET_MOOD", speciesCode: "horse", moodCode: "happy", label: "Horse Happy (Default)", imagePath: "/pet-assets/horse/happy-default.png", starter: true, active: true },
  { code: "horse_sad_default", assetType: "PET_MOOD", speciesCode: "horse", moodCode: "sad", label: "Horse Sad (Default)", imagePath: "/pet-assets/horse/sad-default.png", starter: true, active: true },
  { code: "horse_hungry_default", assetType: "PET_MOOD", speciesCode: "horse", moodCode: "hungry", label: "Horse Hungry (Default)", imagePath: "/pet-assets/horse/hungry-default.png", starter: true, active: true },
  { code: "horse_tired_default", assetType: "PET_MOOD", speciesCode: "horse", moodCode: "tired", label: "Horse Tired (Default)", imagePath: "/pet-assets/horse/tired-default.png", starter: true, active: true },
  { code: "horse_thinking_default", assetType: "PET_MOOD", speciesCode: "horse", moodCode: "thinking", label: "Horse Thinking (Default)", imagePath: "/pet-assets/horse/thinking-default.png", starter: true, active: true },
  { code: "horse_playing_dead_default", assetType: "PET_MOOD", speciesCode: "horse", moodCode: "playing_dead", label: "Horse Playing Dead (Default)", imagePath: "/pet-assets/horse/playing-dead-default.png", starter: true, active: true },
  { code: "parrot_happy_default", assetType: "PET_MOOD", speciesCode: "parrot", moodCode: "happy", label: "Parrot Happy (Default)", imagePath: "/pet-assets/parrot/happy-default.png", starter: true, active: true },
  { code: "parrot_sad_default", assetType: "PET_MOOD", speciesCode: "parrot", moodCode: "sad", label: "Parrot Sad (Default)", imagePath: "/pet-assets/parrot/sad-default.png", starter: true, active: true },
  { code: "parrot_hungry_default", assetType: "PET_MOOD", speciesCode: "parrot", moodCode: "hungry", label: "Parrot Hungry (Default)", imagePath: "/pet-assets/parrot/hungry-default.png", starter: true, active: true },
  { code: "parrot_tired_default", assetType: "PET_MOOD", speciesCode: "parrot", moodCode: "tired", label: "Parrot Tired (Default)", imagePath: "/pet-assets/parrot/tired-default.png", starter: true, active: true },
  { code: "parrot_thinking_default", assetType: "PET_MOOD", speciesCode: "parrot", moodCode: "thinking", label: "Parrot Thinking (Default)", imagePath: "/pet-assets/parrot/thinking-default.png", starter: true, active: true },
  { code: "parrot_playing_dead_default", assetType: "PET_MOOD", speciesCode: "parrot", moodCode: "playing_dead", label: "Parrot Playing Dead (Default)", imagePath: "/pet-assets/parrot/playing-dead-default.png", starter: true, active: true },
  { code: "unicorn_happy_default", assetType: "PET_MOOD", speciesCode: "unicorn", moodCode: "happy", label: "Unicorn Happy (Default)", imagePath: "/pet-assets/unicorn/happy-default.png", starter: true, active: true },
  { code: "unicorn_sad_default", assetType: "PET_MOOD", speciesCode: "unicorn", moodCode: "sad", label: "Unicorn Sad (Default)", imagePath: "/pet-assets/unicorn/sad-default.png", starter: true, active: true },
  { code: "unicorn_hungry_default", assetType: "PET_MOOD", speciesCode: "unicorn", moodCode: "hungry", label: "Unicorn Hungry (Default)", imagePath: "/pet-assets/unicorn/hungry-default.png", starter: true, active: true },
  { code: "unicorn_tired_default", assetType: "PET_MOOD", speciesCode: "unicorn", moodCode: "tired", label: "Unicorn Tired (Default)", imagePath: "/pet-assets/unicorn/tired-default.png", starter: true, active: true },
  { code: "unicorn_thinking_default", assetType: "PET_MOOD", speciesCode: "unicorn", moodCode: "thinking", label: "Unicorn Thinking (Default)", imagePath: "/pet-assets/unicorn/thinking-default.png", starter: true, active: true },
  { code: "unicorn_playing_dead_default", assetType: "PET_MOOD", speciesCode: "unicorn", moodCode: "playing_dead", label: "Unicorn Playing Dead (Default)", imagePath: "/pet-assets/unicorn/playing-dead-default.png", starter: true, active: true },
  { code: "midnight_cat_happy_default", assetType: "PET_MOOD", speciesCode: "midnight_cat", moodCode: "happy", label: "Midnight Cat Happy (Default)", imagePath: "/pet-assets/midnight-cat/happy-default.png", starter: true, active: true },
  { code: "midnight_cat_sad_default", assetType: "PET_MOOD", speciesCode: "midnight_cat", moodCode: "sad", label: "Midnight Cat Sad (Default)", imagePath: "/pet-assets/midnight-cat/sad-default.png", starter: true, active: true },
  { code: "midnight_cat_hungry_default", assetType: "PET_MOOD", speciesCode: "midnight_cat", moodCode: "hungry", label: "Midnight Cat Hungry (Default)", imagePath: "/pet-assets/midnight-cat/hungry-default.png", starter: true, active: true },
  { code: "midnight_cat_tired_default", assetType: "PET_MOOD", speciesCode: "midnight_cat", moodCode: "tired", label: "Midnight Cat Tired (Default)", imagePath: "/pet-assets/midnight-cat/tired-default.png", starter: true, active: true },
  { code: "midnight_cat_thinking_default", assetType: "PET_MOOD", speciesCode: "midnight_cat", moodCode: "thinking", label: "Midnight Cat Thinking (Default)", imagePath: "/pet-assets/midnight-cat/thinking-default.png", starter: true, active: true },
  { code: "midnight_cat_playing_dead_default", assetType: "PET_MOOD", speciesCode: "midnight_cat", moodCode: "playing_dead", label: "Midnight Cat Playing Dead (Default)", imagePath: "/pet-assets/midnight-cat/playing-dead-default.png", starter: true, active: true },
  { code: "panda_happy_default", assetType: "PET_MOOD", speciesCode: "panda", moodCode: "happy", label: "Panda Happy (Default)", imagePath: "/pet-assets/panda/happy-default.png", starter: true, active: true },
  { code: "panda_sad_default", assetType: "PET_MOOD", speciesCode: "panda", moodCode: "sad", label: "Panda Sad (Default)", imagePath: "/pet-assets/panda/sad-default.png", starter: true, active: true },
  { code: "panda_hungry_default", assetType: "PET_MOOD", speciesCode: "panda", moodCode: "hungry", label: "Panda Hungry (Default)", imagePath: "/pet-assets/panda/hungry-default.png", starter: true, active: true },
  { code: "panda_tired_default", assetType: "PET_MOOD", speciesCode: "panda", moodCode: "tired", label: "Panda Tired (Default)", imagePath: "/pet-assets/panda/tired-default.png", starter: true, active: true },
  { code: "panda_thinking_default", assetType: "PET_MOOD", speciesCode: "panda", moodCode: "thinking", label: "Panda Thinking (Default)", imagePath: "/pet-assets/panda/thinking-default.png", starter: true, active: true },
  { code: "panda_playing_dead_default", assetType: "PET_MOOD", speciesCode: "panda", moodCode: "playing_dead", label: "Panda Playing Dead (Default)", imagePath: "/pet-assets/panda/playing-dead-default.png", starter: true, active: true },
  { code: "goldfish_happy_default", assetType: "PET_MOOD", speciesCode: "goldfish", moodCode: "happy", label: "Goldfish Happy (Default)", imagePath: "/pet-assets/goldfish/happy-default.png", starter: true, active: true },
  { code: "goldfish_sad_default", assetType: "PET_MOOD", speciesCode: "goldfish", moodCode: "sad", label: "Goldfish Sad (Default)", imagePath: "/pet-assets/goldfish/sad-default.png", starter: true, active: true },
  { code: "goldfish_hungry_default", assetType: "PET_MOOD", speciesCode: "goldfish", moodCode: "hungry", label: "Goldfish Hungry (Default)", imagePath: "/pet-assets/goldfish/hungry-default.png", starter: true, active: true },
  { code: "goldfish_tired_default", assetType: "PET_MOOD", speciesCode: "goldfish", moodCode: "tired", label: "Goldfish Tired (Default)", imagePath: "/pet-assets/goldfish/tired-default.png", starter: true, active: true },
  { code: "goldfish_thinking_default", assetType: "PET_MOOD", speciesCode: "goldfish", moodCode: "thinking", label: "Goldfish Thinking (Default)", imagePath: "/pet-assets/goldfish/thinking-default.png", starter: true, active: true },
  { code: "goldfish_playing_dead_default", assetType: "PET_MOOD", speciesCode: "goldfish", moodCode: "playing_dead", label: "Goldfish Playing Dead (Default)", imagePath: "/pet-assets/goldfish/playing-dead-default.png", starter: true, active: true },
  { code: "lizard_happy_default", assetType: "PET_MOOD", speciesCode: "lizard", moodCode: "happy", label: "Lizard Happy (Default)", imagePath: "/pet-assets/lizard/happy-default.png", starter: true, active: true },
  { code: "lizard_sad_default", assetType: "PET_MOOD", speciesCode: "lizard", moodCode: "sad", label: "Lizard Sad (Default)", imagePath: "/pet-assets/lizard/sad-default.png", starter: true, active: true },
  { code: "lizard_hungry_default", assetType: "PET_MOOD", speciesCode: "lizard", moodCode: "hungry", label: "Lizard Hungry (Default)", imagePath: "/pet-assets/lizard/hungry-default.png", starter: true, active: true },
  { code: "lizard_tired_default", assetType: "PET_MOOD", speciesCode: "lizard", moodCode: "tired", label: "Lizard Tired (Default)", imagePath: "/pet-assets/lizard/tired-default.png", starter: true, active: true },
  { code: "lizard_thinking_default", assetType: "PET_MOOD", speciesCode: "lizard", moodCode: "thinking", label: "Lizard Thinking (Default)", imagePath: "/pet-assets/lizard/thinking-default.png", starter: true, active: true },
  { code: "lizard_playing_dead_default", assetType: "PET_MOOD", speciesCode: "lizard", moodCode: "playing_dead", label: "Lizard Playing Dead (Default)", imagePath: "/pet-assets/lizard/playing-dead-default.png", starter: true, active: true },
  { code: "bg_aurora_default", assetType: "BACKGROUND", speciesCode: "all", moodCode: "", label: "Aurora Hills", imagePath: "/cosmetic-staging/backgrounds/theme-aurora.svg", starter: false, active: true },
  { code: "bg_candy_default", assetType: "BACKGROUND", speciesCode: "all", moodCode: "", label: "Candy Dream", imagePath: "/cosmetic-staging/backgrounds/theme-candy.svg", starter: false, active: true },
  { code: "bg_dusk_default", assetType: "BACKGROUND", speciesCode: "all", moodCode: "", label: "Dusk Glow", imagePath: "/cosmetic-staging/backgrounds/theme-dusk.svg", starter: false, active: true },
  { code: "bg_underwater_default", assetType: "BACKGROUND", speciesCode: "all", moodCode: "", label: "Underwater", imagePath: "/cosmetic-staging/backgrounds/theme-underwater.svg", starter: false, active: true },
  { code: "fg_soft_vignette_default", assetType: "FOREGROUND", speciesCode: "all", moodCode: "", label: "Soft vignette (free)", imagePath: "/cosmetic-staging/foregrounds/soft-vignette.svg", starter: true, active: true },
  { code: "fg_sparkle_default", assetType: "FOREGROUND", speciesCode: "all", moodCode: "", label: "Sparkle frame", imagePath: "/cosmetic-staging/foregrounds/sparkle-frame.svg", starter: false, active: true }
]);

db.minigames.deleteMany({});
db.minigames.insertMany([
  {
    code: "higher_lower",
    name: "Higher or Lower",
    description: "Guess if the next random number from 1 to 100 will be higher or lower.",
    energyCost: 3,
    active: true,
    rewardStrategy: { type: "SHIFTED_FIBONACCI", sequenceStart: [1, 2], maxReward: 48 },
    happinessImpactStrategy: {
      type: "SCORE_THRESHOLDS",
      thresholds: [
        { minScore: 0, maxScore: 0, happinessDeltaPercent: -0.1 },
        { minScore: 1, maxScore: 1, happinessDeltaPercent: 0.0 },
        { minScore: 2, maxScore: 999, happinessDeltaPercentPerPoint: 0.125, maxPositivePercent: 0.625 }
      ]
    }
  },
  {
    code: "puzzle_swap",
    name: "Puzzle Swap",
    description: "Rebuild shuffled image by swapping two tiles.",
    energyCost: 4,
    active: true,
    rewardStrategy: { type: "SCORE_LINEAR", coinsPerPoint: 2, maxReward: 96 },
    happinessImpactStrategy: { type: "SCORE_THRESHOLDS" }
  },
  {
    code: "connect4_ai",
    name: "Connect 4 AI",
    description: "Play Connect 4 against AI with multiple difficulty levels.",
    energyCost: 5,
    active: true,
    rewardStrategy: { type: "CONNECT4_OUTCOME", rewards: { win: 9, draw: 4, loss: 1 } },
    happinessImpactStrategy: { type: "SCORE_THRESHOLDS" }
  },
  {
    code: "minesweep_ai",
    name: "Minesweeper",
    description: "Clear the field without hitting a mine. Mines are placed after your first reveal (safe first click).",
    energyCost: 4,
    active: true,
    rewardStrategy: { type: "CONNECT4_OUTCOME", rewards: { win: 10, draw: 0, loss: 1 } },
    happinessImpactStrategy: { type: "SCORE_THRESHOLDS" }
  },
  {
    code: "checkers_ai",
    name: "Checkers vs AI",
    description: "American checkers on an 8×8 board. Capture when available. Three AI strengths.",
    energyCost: 5,
    active: true,
    rewardStrategy: { type: "CONNECT4_OUTCOME", rewards: { win: 8, draw: 3, loss: 1 } },
    happinessImpactStrategy: { type: "SCORE_THRESHOLDS" }
  }
]);
db.owned_cosmetics.deleteMany({});
db.pet_colors.deleteMany({});
db.pet_shapes.deleteMany({});
