spring.datasource.url=jdbc:postgresql://localhost:5432/reading_tracker
spring.datasource.username=reading_tracker
spring.datasource.password=reading_tracker
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
