create table if not exists activity_events (
    id bigint generated by default as identity primary key,
    user_id varchar(100) not null,
    event_type varchar(100) not null,
    source varchar(100) not null,
    happened_at timestamp with time zone not null,
    pet_name varchar(64),
    species_code varchar(32),
    hunger double precision,
    happiness double precision,
    energy double precision,
    coin_balance integer,
    metadata_json text not null
);

create index if not exists idx_activity_events_user_happened_at
    on activity_events (user_id, happened_at desc);

create index if not exists idx_activity_events_type_happened_at
    on activity_events (event_type, happened_at desc);

create table if not exists achievement_definitions (
    id bigint generated by default as identity primary key,
    code varchar(100) not null unique,
    title varchar(120) not null,
    description varchar(500) not null,
    category varchar(60) not null,
    trigger_event_type varchar(100) not null,
    required_count integer not null,
    active boolean not null,
    sort_order integer not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists user_achievements (
    id bigint generated by default as identity primary key,
    user_id varchar(100) not null,
    achievement_code varchar(100) not null,
    progress_count integer not null,
    unlocked_at timestamp with time zone,
    last_event_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uq_user_achievements_user_code unique (user_id, achievement_code)
);

create index if not exists idx_user_achievements_user_updated
    on user_achievements (user_id, updated_at desc);

create table if not exists notification_preferences (
    id bigint generated by default as identity primary key,
    user_id varchar(100) not null unique,
    low_hunger_enabled boolean not null,
    daily_ai_summary_enabled boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

insert into achievement_definitions (
    code,
    title,
    description,
    category,
    trigger_event_type,
    required_count,
    active,
    sort_order,
    created_at,
    updated_at
) values
    ('pet_namer', 'Name Tag', 'Give your pet a custom name for the first time.', 'pet', 'PET_RENAMED', 1, true, 10, current_timestamp, current_timestamp),
    ('shopper_first', 'First Purchase', 'Buy your first item from the shop.', 'economy', 'SHOP_PURCHASED', 1, true, 20, current_timestamp, current_timestamp),
    ('minigame_regular', 'Playful Start', 'Finish any minigame three times.', 'minigame', 'MINIGAME_FINISHED', 3, true, 30, current_timestamp, current_timestamp),
    ('pet_chatter', 'First Conversation', 'Send your pet its first AI chat message.', 'ai', 'AI_CHAT_SENT', 1, true, 40, current_timestamp, current_timestamp);
