create table if not exists notification_deliveries (
    id bigint generated by default as identity primary key,
    user_id varchar(100) not null,
    kind varchar(100) not null,
    delivery_key varchar(180) not null unique,
    target_email varchar(255) not null,
    subject varchar(255) not null,
    body_preview varchar(1000) not null,
    success boolean not null,
    response_message varchar(1000),
    created_at timestamp with time zone not null
);

create index if not exists idx_notification_deliveries_user_kind_created
    on notification_deliveries (user_id, kind, created_at desc);
