create table if not exists daily_challenge_definitions (
    id bigint generated by default as identity primary key,
    challenge_date date not null,
    slot_order integer not null,
    challenge_type varchar(60) not null,
    trigger_event_type varchar(100) not null,
    match_value varchar(120) not null,
    title varchar(160) not null,
    description varchar(500) not null,
    required_count integer not null,
    reward_coins integer not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uq_daily_challenge_definitions_date_slot unique (challenge_date, slot_order)
);

create index if not exists idx_daily_challenge_definitions_date
    on daily_challenge_definitions (challenge_date, slot_order);

create table if not exists user_daily_challenge_progress (
    id bigint generated by default as identity primary key,
    user_id varchar(100) not null,
    challenge_definition_id bigint not null,
    progress_count integer not null,
    completed_at timestamp with time zone,
    reward_granted boolean not null,
    reward_granted_at timestamp with time zone,
    last_event_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uq_user_daily_challenge_progress unique (user_id, challenge_definition_id)
);

create index if not exists idx_user_daily_challenge_progress_user_updated
    on user_daily_challenge_progress (user_id, updated_at desc);
